package com.ofemmy.librarymanager.models;

public enum BookCategory {
  FANTASY, ADVENTURE, ROMANCE, CONTEMPORARY, DYSTOPIAN, MYSTERY, HORROR, THRILLER, PARANORMAL, HISTORICAL_FICTION,
  SCIENCE_FICTION, MEMOIR, COOKING, ART, DEVELOPMENT, HEALTH, HISTORY, TRAVEL, GUIDE, FAMILY_AND_RELATIONSHIP,
  HUMOR, CHILDREN
}
